--------------------------------------------------------
-- Archivo creado  - viernes-julio-26-2024   
--------------------------------------------------------

--------------------------------------------------------
--  CREACION DE USUARIO PARA CONECCION CON EL PROGRAMA
--------------------------------------------------------


ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER TATA IDENTIFIED BY adminadmin;
GRANT CONNECT, RESOURCE, DBA TO TATA;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO TATA;
GRANT UNLIMITED TABLESPACE TO TATA;

COMMIT;

--------------------------------------------------------
--  A PARTIR DE ESTA PARTE SE GENERO EL BACKUP AUTOMATICO DESDE ORACLE, SIN EMBARGO EL PROGRAMA CREA 
-- AUTOMATICAMENTE LAS TABLAS POR LO QUE NO ES NECESARIO CORRER ESTA PARTE DEL QUERY, PERO SE ADJUNTA 
-- COMO RESPALDO PARA CREAR LAS TABLAS. 
-- PARA LLENAR LAS TABLAS, SOLO ES NECESARIO CORRER LOS ARCHIVOS DE POSTMAN 
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "TATA"."CLIENTES" 
   (	"CLIENTE_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DIRECCION" VARCHAR2(100 CHAR), 
	"EDAD" NUMBER(10,0), 
	"GENERO" VARCHAR2(1 CHAR), 
	"IDENTIFICACION" VARCHAR2(10 CHAR), 
	"NOMBRE" VARCHAR2(75 CHAR), 
	"TELEFONO" VARCHAR2(10 CHAR), 
	"CONTRASENA" VARCHAR2(100 CHAR), 
	"ESTADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUENTAS
--------------------------------------------------------

  CREATE TABLE "TATA"."CUENTAS" 
   (	"CUENTA_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CLIENTE_ID" NUMBER(10,0), 
	"ESTADO" NUMBER(1,0), 
	"NUMERO_CUENTA" VARCHAR2(255 CHAR), 
	"SALDO_DISPONIBLE" FLOAT(53), 
	"SALDO_INICIAL" FLOAT(53), 
	"TIPO_CUENTA" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "TATA"."MOVIMIENTOS" 
   (	"MOVIMIENTO_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA" TIMESTAMP (6), 
	"NUMERO_CUENTA" VARCHAR2(255 CHAR), 
	"SALDO" FLOAT(53), 
	"TIPO_MOVIMIENTO" VARCHAR2(1 CHAR), 
	"VALOR" FLOAT(53)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008822
--------------------------------------------------------

  CREATE UNIQUE INDEX "TATA"."SYS_C008822" ON "TATA"."CLIENTES" ("CLIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008825
--------------------------------------------------------

  CREATE UNIQUE INDEX "TATA"."SYS_C008825" ON "TATA"."CUENTAS" ("CUENTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008830
--------------------------------------------------------

  CREATE UNIQUE INDEX "TATA"."SYS_C008830" ON "TATA"."MOVIMIENTOS" ("MOVIMIENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "TATA"."CLIENTES" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("EDAD" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CLIENTES" ADD CHECK (estado in (0,1)) ENABLE;
  ALTER TABLE "TATA"."CLIENTES" ADD PRIMARY KEY ("CLIENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUENTAS
--------------------------------------------------------

  ALTER TABLE "TATA"."CUENTAS" MODIFY ("CUENTA_ID" NOT NULL ENABLE);
  ALTER TABLE "TATA"."CUENTAS" ADD CHECK (estado in (0,1)) ENABLE;
  ALTER TABLE "TATA"."CUENTAS" ADD PRIMARY KEY ("CUENTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "TATA"."MOVIMIENTOS" MODIFY ("MOVIMIENTO_ID" NOT NULL ENABLE);
  ALTER TABLE "TATA"."MOVIMIENTOS" MODIFY ("NUMERO_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "TATA"."MOVIMIENTOS" MODIFY ("TIPO_MOVIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "TATA"."MOVIMIENTOS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "TATA"."MOVIMIENTOS" ADD PRIMARY KEY ("MOVIMIENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


